// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	Email        string
	CreatedAt    pgtype.Timestamptz
	PasswordHash []byte
	Active       bool
	Role         string
}
