// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT email, created_at, password_hash, active, role FROM auth.users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i AuthUser
	err := row.Scan(
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.Active,
		&i.Role,
	)
	return i, err
}
